---
- name: Provision workers
  shell: >
    kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }}
    --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}
    {{ item }}:{{ kubernetes_apiserver_port }}
  with_items: "{{ groups['master'] }}"

