---
kubernetes_version: '1.15'
kubernetes_pod_network_cidr: '10.244.0.0/16'
kubernetes_version_kubeadm: 'stable-{{ kubernetes_version }}'

kubelet_args_path: '/etc/systemd/system/kubelet.service.d/90-local-extras.conf'
kubelet_args_line: 'Environment=\"KUBELET_EXTRA_ARGS=--fail-swap-on=false\"'

kubernetes_flannel_manifest_file: 'https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml'

kubernetes_apiserver_port: '6443'
